Add navigation bar component
padaiyal/jsReactMaterialUIExtras pull request #12
Opened 2021-01-29 08:39 UTC by ngkelly

## Description
Add a navigation bar component

Fixes #1.

## Author's Checklist
- [ ] **These changes don't break existing dependants.** If they do, and you suggest to proceed, 
please explain why.

## Reviewer's Checklist
- [ ] **All classes have documentation comments.**
- [ ] **All methods have documentation comments.**
- [ ] **No parameters are hardcoded.** Should be loaded as properties instead. If there needs to be hardcoded properties, explain why.
- [ ] **All information to be logged/displayed to the user are internationalized.** If not, explain why. 
- [ ] **README.md has been updated if needed.**

## Assignee's Checklist
- [ ] **All GitHub action checks have passed.**
- [ ] **All reviewers have approved.**
- [ ] **Relevant documentation has been updated if needed.**

2021-01-29 15:30 UTC, the-c0d3br34k3r requested changes
Reviewed. Please complete the author's checklist as well.

2021-01-29 15:30 UTC, the-c0d3br34k3r commented on sample_app/src/App.js
> +            tabNames: ["Tab One", "Tab Two", "Tab Three", "Tab Four"],
Would it be better to have a single JSON array instead of two arrays?

2021-01-29 22:49 UTC, ngkelly commented on sample_app/src/App.js
> +            tabNames: ["Tab One", "Tab Two", "Tab Three", "Tab Four"],
Yes, this has now been changed to a single JSON array.

2021-01-30 00:06 UTC, the-c0d3br34k3r commented on README.md
> +<NavBar companyLogo={companyLogo} tabs={this.state.tabs}/>
How does `this.state.tabs` look like? Please show that as well.

2021-01-30 00:08 UTC, the-c0d3br34k3r requested changes
Requested changes to README.md.

2021-01-30 01:16 UTC, ngkelly commented on README.md
> +<NavBar companyLogo={companyLogo} tabs={this.state.tabs}/>
I have included it as well.

2021-01-30 03:42 UTC, the-c0d3br34k3r approved these changes

2021-01-30 03:42 UTC, merged